version: 0.2

phases:
  build:
    commands:
      - cd frontend
      - npm install
      - npm run build
artifacts:
  files:
    - dist/**/*
    - application.py
    - summary_parser.py
    - summary_plotters.py
    - requirements.txt
    - .ebextensions/**/*
